service: smiles-helper

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x

functions:
  promotions:
    handler: aws/lambda/promotions.getPromotions
    timeout: 600
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:749264263523:smiles-helper-alerts
          functionResponseType: ReportBatchItemFailures
  removePreferences:
    handler: aws/lambda/preferences.removePreferences
    events:
      - httpApi:
          method: DELETE
          path: /preferences/{username}
  getMonthlyFlights:
    handler: aws/lambda/search.getMonthlyFlights
    timeout: 120
    events:
      - httpApi:
          method: GET
          path: /search_month
  getRegionalFlights:
    handler: aws/lambda/search.getRegionalFlights
    timeout: 120
    events:
     - httpApi:
        method: GET
        path: /search_regional
  getRoundTripFlights:
    handler: aws/lambda/search.getRoundTripFlights
    timeout: 120
    events:
      - httpApi:
          method: GET
          path: /search_round_trip

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

