service: smiles-helper

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x

functions:
  promotions:
    handler: aws/lambda/promotions.getPromotions
    timeout: 600
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:749264263523:smiles-helper-alerts
          functionResponseType: ReportBatchItemFailures
  removeFilters:
    handler: aws/lambda/filters.removeFilters
    events:
      - httpApi:
          method: DELETE
          path: /filters/{username}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

