org: juanidambrosio
app: smiles-helper
service: smiles-helper

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    MONGO_URL: ${env:MONGO_URL}

functions:
  webhookMP:
    handler: aws/lambda/mpWebhook.handleMPWebhook
    events:
      - httpApi:
          method: POST
          path: /webhook/mercadopago
    memorySize: 128
    timeout: 10
  
  # promotions:
  #   enabled: false
  #   handler: aws/lambda/promotions.getPromotions
  #   timeout: 30
  #   events:
  #     - sqs:
  #         arn: arn:aws:sqs:us-east-1:749264263523:smiles-helper-alerts
  #         functionResponseType: ReportBatchItemFailures
  
  # removePreferences:
  #   enabled: false
  #   handler: aws/lambda/preferences.removePreferences
  #   events:
  #     - httpApi:
  #         method: DELETE
  #         path: /preferences/{username}
  
  # getMonthlyFlights:
  #   enabled: false
  #   handler: aws/lambda/search.getMonthlyFlights
  #   timeout: 30
  #   events:
  #     - httpApi:
  #         method: GET
  #         path: /search_month
  
  # getRegionalFlights:
  #   enabled: false
  #   handler: aws/lambda/search.getRegionalFlights
  #   timeout: 30
  #   events:
  #    - httpApi:
  #       method: GET
  #       path: /search_regional
  
  # getRoundTripFlights:
  #   enabled: false
  #   handler: aws/lambda/search.getRoundTripFlights
  #   timeout: 30
  #   events:
  #     - httpApi:
  #         method: GET
  #         path: /search_round_trip

plugins:
  - serverless-offline